// Centralized Subject Areas config used across the app.
// If you need to add or update a subject area or category, do it here.
export const SUBJECT_AREAS = {
  "Agricultural and Biological Sciences": [
    "Agronomy and Crop Science",
    "Animal Science and Zoology",
    "Aquatic Science",
    "Ecology, Evolution, Behavior and Systematics",
    "Food Science",
    "Forestry",
    "Horticulture",
    "Insect Science",
    "Plant Science",
    "Soil Science",
    "Agricultural and Biological Sciences (miscellaneous)",
  ],
  "Arts and Humanities": [
    "Archeology",
    "Arts and Humanities (miscellaneous)",
    "Classics",
    "Conservation",
    "History",
    "History and Philosophy of Science",
    "Language and Linguistics",
    "Literature and Literary Theory",
    "Music",
    "Philosophy",
    "Religious Studies",
    "Visual Arts and Performing Arts",
  ],
  "Biochemistry, Genetics and Molecular Biology": [
    "Aging",
    "Biochemistry",
    "Biochemistry, Genetics and Molecular Biology (miscellaneous)",
    "Biophysics",
    "Biotechnology",
    "Cancer Research",
    "Cell Biology",
    "Clinical Biochemistry",
    "Developmental Biology",
    "Endocrinology",
    "Genetics",
    "Molecular Biology",
    "Molecular Medicine",
    "Structural Biology",
  ],
  "Business, Management and Accounting": [
    "Accounting",
    "Business and International Management",
    "Business, Management and Accounting (miscellaneous)",
    "Industrial and Manufacturing Engineering",
    "Management Information Systems",
    "Management of Technology and Innovation",
    "Marketing",
    "Organizational Behavior and Human Resource Management",
    "Strategy and Management",
    "Tourism, Leisure and Hospitality Management",
  ],
  "Chemical Engineering": [
    "Bioengineering",
    "Catalysis",
    "Chemical Engineering (miscellaneous)",
    "Chemical Health and Safety",
    "Colloid and Surface Chemistry",
    "Filtration and Separation",
    "Fluid Flow and Transfer Processes",
    "Process Chemistry and Technology",
  ],
  Chemistry: [
    "Analytical Chemistry",
    "Chemistry (miscellaneous)",
    "Electrochemistry",
    "Inorganic Chemistry",
    "Organic Chemistry",
    "Physical and Theoretical Chemistry",
    "Spectroscopy",
  ],
  "Computer Science": [
    "Artificial Intelligence",
    "Computational Theory and Mathematics",
    "Computer Graphics and Computer-Aided Design",
    "Computer Networks and Communications",
    "Computer Science Applications",
    "Computer Science (miscellaneous)",
    "Computer Vision and Pattern Recognition",
    "Hardware and Architecture",
    "Human-Computer Interaction",
    "Information Systems",
    "Signal Processing",
    "Software",
  ],
  "Decision Sciences": [
    "Decision Sciences (miscellaneous)",
    "Information Systems and Management",
    "Management Science and Operations Research",
  ],
  "Earth and Planetary Sciences": [
    "Atmospheric Science",
    "Computers in Earth Sciences",
    "Earth and Planetary Sciences (miscellaneous)",
    "Earth-Surface Processes",
    "Economic Geology",
    "Geochemistry and Petrology",
    "Geology",
    "Geophysics",
    "Geotechnical Engineering and Engineering Geology",
    "Oceanography",
    "Paleontology",
    "Space and Planetary Science",
    "Stratigraphy",
  ],
  "Economics, Econometrics and Finance": [
    "Economics and Econometrics",
    "Economics, Econometrics and Finance (miscellaneous)",
    "Finance",
  ],
  Energy: [
    "Energy Engineering and Power Technology",
    "Energy (miscellaneous)",
    "Fuel Technology",
    "Nuclear Energy and Engineering",
    "Renewable Energy, Sustainability and the Environment",
  ],
  Engineering: [
    "Aerospace Engineering",
    "Automotive Engineering",
    "Biomedical Engineering",
    "Civil and Structural Engineering",
    "Control and Systems Engineering",
    "Electrical and Electronic Engineering",
    "Engineering (miscellaneous)",
    "Industrial and Manufacturing Engineering",
    "Mechanical Engineering",
    "Ocean Engineering",
    "Safety, Risk, Reliability and Quality",
  ],
  "Environmental Science": [
    "Ecological Modeling",
    "Ecology",
    "Environmental Chemistry",
    "Environmental Engineering",
    "Environmental Science (miscellaneous)",
    "Global and Planetary Change",
    "Health, Toxicology and Mutagenesis",
    "Management, Monitoring, Policy and Law",
    "Nature and Landscape Conservation",
    "Pollution",
    "Waste Management and Disposal",
    "Water Science and Technology",
  ],
  "Immunology and Microbiology": [
    "Applied Microbiology and Biotechnology",
    "Immunology",
    "Immunology and Microbiology (miscellaneous)",
    "Microbiology",
    "Parasitology",
    "Virology",
  ],
  "Materials Science": [
    "Biomaterials",
    "Ceramics and Composites",
    "Electronic, Optical and Magnetic Materials",
    "Materials Chemistry",
    "Materials Science (miscellaneous)",
    "Metals and Alloys",
    "Polymers and Plastics",
    "Surfaces, Coatings and Films",
  ],
  Mathematics: [
    "Algebra and Number Theory",
    "Analysis",
    "Applied Mathematics",
    "Computational Mathematics",
    "Control and Optimization",
    "Discrete Mathematics and Combinatorics",
    "Geometry and Topology",
    "Logic",
    "Mathematical Physics",
    "Mathematics (miscellaneous)",
    "Modeling and Simulation",
    "Numerical Analysis",
    "Statistics and Probability",
    "Theoretical Computer Science",
  ],
  Medicine: [
    "Anesthesiology and Pain Medicine",
    "Biochemistry (medical)",
    "Cardiology and Cardiovascular Medicine",
    "Critical Care and Intensive Care Medicine",
    "Complementary and Alternative Medicine",
    "Dermatology",
    "Drug Discovery",
    "Emergency Medicine",
    "Endocrinology, Diabetes and Metabolism",
    "Epidemiology",
    "Family Practice",
    "Gastroenterology",
    "Geriatrics and Gerontology",
    "Health Informatics",
    "Health Policy",
    "Hematology",
    "Hepatology",
    "Histology and Pathology",
    "Immunology and Allergy",
    "Internal Medicine",
    "Medicine (miscellaneous)",
    "Microbiology (medical)",
    "Nephrology",
    "Neurology (clinical)",
    "Obstetrics and Gynecology",
    "Oncology",
    "Ophthalmology",
    "Orthopedics and Sports Medicine",
    "Otorhinolaryngology",
    "Pathology and Forensic Medicine",
    "Pediatrics, Perinatology and Child Health",
    "Pharmacology (medical)",
    "Physiology (medical)",
    "Psychiatry and Mental Health",
    "Public Health, Environmental and Occupational Health",
    "Pulmonary and Respiratory Medicine",
    "Radiology, Nuclear Medicine and Imaging",
    "Rehabilitation",
    "Reproductive Medicine",
    "Reviews and References (medical)",
    "Rheumatology",
    "Surgery",
    "Transplantation",
    "Urology",
  ],
};